services:
    form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        autowire: true

    jwt_authenticator:
        class: AppBundle\Security\JwtAuthenticator
        autowire: true

    spooky_user_provider:
        class: AppBundle\Security\SpookyUserProvider
        arguments:
            - '@doctrine.orm.entity_manager'
