services:
    form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'

    api_token_authenticator:
        class: AppBundle\Security\ApiTokenAuthenticator
        arguments:
            - '@doctrine.orm.entity_manager'

    api_facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        arguments:
            - '@service_container'

    spooky_user_provider:
        class: AppBundle\Security\SpookyUserProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    app.facebook_provider:
        class: League\OAuth2\Client\Provider\Facebook
        arguments:
            -
                clientId: %facebook_app_id%
                clientSecret: %facebook_app_secret%
                graphApiVersion: v2.3
                redirectUri: "@=service('router').generate('connect_facebook_check', {}, true)"
