services:
    form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'

    api_token_authenticator:
        class: AppBundle\Security\ApiTokenAuthenticator
        arguments:
            - '@doctrine.orm.entity_manager'

    spooky_user_provider:
        class: AppBundle\Security\SpookyUserProvider
        arguments:
            - '@doctrine.orm.entity_manager'
